"""Generate a lookup table of Bessel function zeros and write to src/bessel_zeros.js"""

from scipy.special import jn_zeros
import json

MAX_ORDER = 32

# zeros[m][i] = (i+1)th zero of J_m
zeros = {}
for m in range(MAX_ORDER):
    zeros[m] = jn_zeros(m, MAX_ORDER).tolist()

with open("src/bessel_zeros.js", "w") as f:
    f.write("// Auto-generated by generate_zeros.py\n")
    f.write(f"// BESSEL_ZEROS[m][n-1] = nth zero of J_m, for m=0..{MAX_ORDER-1}, n=1..{MAX_ORDER}\n")
    f.write(f"export const BESSEL_ZEROS = {json.dumps(zeros, indent=2)};\n")

print(f"Wrote src/bessel_zeros.js with zeros for m=0..{MAX_ORDER-1}, n=1..{MAX_ORDER}")
